__author__ = 'Vincent'

BDD_TYPE = 'sqlite'
BDD_NAME = 'karttracker.db'
BDD_STRING_CONNECTION = BDD_TYPE + ':///' + BDD_NAME

PIN_NUMBER_BUTTON = 21
PIN_NUMBER_LED = 20
PIN_NUMBER_RUNING = 16

REST_ADDRESS = "http://192.168.1.101:4000/"